[package]
name = "flux"
version = "0.5.1"
authors = ["jlapacik <joshua.lapacik@pacbell.net>"]
edition = "2018"

[lib]
name = "flux"
crate-type = ["rlib", "staticlib", "cdylib"]

[features]
default = ["strict"]
strict = []

[dependencies]
core = { path = "../core" }
flatbuffers = "0.6.0"
serde = "^1.0.59"
serde_derive = "^1.0.59"
serde_json = "1.0"
serde-aux = "0.6.1"
wasm-bindgen = { version = "0.2.62", features = ["serde-serialize"] }

[dev-dependencies]
maplit = "1.0.2"
criterion = "0.3.3"

[build-dependencies]
core = { path = "../core" }
flatbuffers = "0.6.0"

[[bench]]
name = "builtins"
harness = false

[[bench]]
name = "basic"
harness = false

[[bench]]
name = "formatter"
harness = false

[[bench]]
name = "bench_scanner"
path = "benches/benchmarks.rs"
harness = false
