[package]
name = "flux"
version = "0.5.1"
authors = ["jlapacik <joshua.lapacik@pacbell.net>"]
edition = "2018"

[lib]
name = "flux"
crate-type = ["rlib", "staticlib", "cdylib"]

[[bin]]
name = "flux-dump-docs"
test = false
bench = false

[features]
default = ["strict"]
strict = []

[dependencies]
comrak = "0.10.1"
flux-core = { path = "../flux-core" }
flatbuffers = "2.0.0"
lazy_static = "1.4.0"
serde = "^1.0.59"
serde_derive = "^1.0.59"
serde_json = "1.0"
serde-aux = "0.6.1"
structopt = "0.3.13"
tera = "1"
inflate = "0.4.5"

# `getrandom` is a dependency of the `tera` crate, which does not support
# the wasm32-unknown-unknown target by default. Explicitly importing it here
# allows us to enable that support with the "js" feature.
# For details, see 'https://docs.rs/getrandom/0.2.3/getrandom/#webassembly-support'
[dependencies.getrandom]
version = "0.2"
features = ["js"]

[dev-dependencies]
maplit = "1.0.2"
criterion = "0.3.3"

[build-dependencies]
flux-core = { path = "../flux-core" }
serde_json = "1.0"
flatbuffers = "2.0.0"
deflate = "0.9.1"

[[bench]]
name = "builtins"
harness = false

[[bench]]
name = "basic"
harness = false

[[bench]]
name = "formatter"
harness = false
