[toolchain]
channel = "1.62"
components = ["rustfmt", "clippy"]
targets = [
    "wasm32-unknown-unknown",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "x86_64-pc-windows-gnu",
    "x86_64-apple-darwin",
]
