[package]
name = "parser"
version = "0.1.0"
authors = ["Nathaniel Cook <nathaniel@influxdata.com>"]
edition = "2018"

[dependencies]
libc = "0.2.0"
regex = "1"

[build-dependencies]
cc = "1.0"
bindgen = "0.49.0"
