[package]
name = "parser"
version = "0.1.0"
authors = ["Nathaniel Cook <nathaniel@influxdata.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = "^1.0.59"
serde_derive = "^1.0.59"

[build-dependencies]
cc = "1.0"
bindgen = "0.49.0"
